# Generated by Django 4.0.4 on 2022-06-10 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('django_app', '0003_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_app.order'),
            preserve_default=False,
        ),
    ]
