# Generated by Django 4.0.4 on 2022-06-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_orderitem_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-06-10'),
            preserve_default=False,
        ),
    ]
